.Dd May 11, 2017
.Dt GEN 1
.Os

.Sh NAME
.Nm gen
.Nd generate generic names

.Sh SYNOPSIS
.Nm
.Ar count

.Sh DESCRIPTION
.Nm
prints generic, lowercase, ascending alphabetic names, specified by
.Ar count .
If
.Ar count
is numeric, exactly count names will be printed, if it is alphabetic,
all names of the same length up to count are printed. The names
are separated by newlines.

.Sh EXAMPLES
Print the alphabet:
.Pp
.Dl $ gen z
.Dl a
.Dl b
.Dl ...
.Dl z
.Pp
Print every string from
.Sq aaa
to
.Sq gen :
.Pp
.Dl $ gen 4174
.Dl aaa
.Dl aab
.Dl ...
.Dl gen

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr seq 1 ,
and
.Xr perl 1perl ,
which can do string incrementation as well.

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.de
