.TH GEN 1
.SH NAME
gen \- generate generic names

.SH SYNOPSIS
gen COUNT

.SH DESCRIPTION
gen prints generic names, determined by the argument COUNT.
If COUNT is numeric, exactly COUNT names of all the same length are printed,
if it is alphabetic, all names of the same length up to COUNT are printed.
The generic names are separated by newlines.

.SH EXAMPLES
.PP
.fi
.RS
$ gen z
.RE
.fi
prints the alphabet, as well as gen 26.
.PP
.fi
.RS
gen 17576
.RE
.fi
prints every string from 'aaa' to 'zzz'.

.SH STATUS
0 on success and 1 when it prints the usage.

.SH BUGS
The code probably sucks.
.PP
It does not take any file names as arguments, you have to use
shell redirection or cat.

.SH "SEE ALSO"
.IR seq(1),
.IR perl(1)
(which can do string increment)

.SH AUTHOR
Praise at pranomestro@gmail.com
